#[derive(Debug)]
pub enum Key {
    Unknown,
    Backspace,
    Tab,
    Return,
    Esc,
    Space,
    PageUp,
    PageDown,
    End,
    Home,
    Left,
    Right,
    Down,
    Insert,
    Delete,
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Tilda,
}

impl From<u32> for Key {
    fn from(v: u32) -> Key {
        match v {
            8 => Key::Backspace,
            9 => Key::Tab,
            13 => Key::Return,
            27 => Key::Esc,
            32 => Key::Space,
            33 => Key::PageUp,
            34 => Key::PageDown,
            35 => Key::End,
            36 => Key::Home,
            37 => Key::Left,
            39 => Key::Right,
            40 => Key::Down,
            45 => Key::Insert,
            46 => Key::Delete,
            48 => Key::Zero,
            49 => Key::One,
            50 => Key::Two,
            51 => Key::Three,
            52 => Key::Four,
            53 => Key::Five,
            54 => Key::Six,
            55 => Key::Seven,
            56 => Key::Eight,
            57 => Key::Nine,
            65 => Key::A,
            66 => Key::B,
            67 => Key::C,
            68 => Key::D,
            69 => Key::E,
            70 => Key::F,
            71 => Key::G,
            72 => Key::H,
            73 => Key::I,
            74 => Key::J,
            75 => Key::K,
            76 => Key::L,
            77 => Key::M,
            78 => Key::N,
            79 => Key::O,
            80 => Key::P,
            81 => Key::Q,
            82 => Key::R,
            83 => Key::S,
            84 => Key::T,
            85 => Key::U,
            86 => Key::V,
            87 => Key::W,
            88 => Key::X,
            89 => Key::Y,
            90 => Key::Z,
            192 => Key::Tilda,
            _ => Key::Unknown,
        }
    }
}
